use_frameworks!

platform :ios, '8.0'

target 'PandoraBox_Example' do
  pod 'PandoraBox', :path => '../'

  target 'PandoraBox_Tests' do
    inherit! :search_paths
    
    # pod 'Specta'
    # pod 'Expecta'
    # pod 'FBSnapshotTestCase'
    # pod 'Expecta+Snapshots'
  end
end
